version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-197-228-62.compute-1.amazonaws.com
            port: '5432'
            database: d83t14lg523v0r
            schema: schema.graphql
            user: ujedlisbnvaxbm
            password: cd901bf009aff9904153eae707a1a8017181717a1184eff1812c3924e62b492b
            migrations: true